### ISSUE TITLE
Publish research that has been executed by one single organization

### ISSUE THREAD

**Issue by robnyman** [web-platform-dx/developer-research#16]
I'm curious in this group's thoughts around publishing research that has been executed by one single organization. There are cases where we might make results public, which we believe would benefit the larger platform, and I'm interested in your take on this?

Also, what kind of information around executed research would make it easier to understand the approach and hopefully limit the worry for bias? Would it be transparency around methodology, target group for the audience etc?

**Comment by dontcallmedom** [comment]
I see a lot of potential value in sharing publicly single organization results, esp if they come with the level of transparency we're discussing for our own work with MDN short surveys #9:
* if there are biases that emerge from reviewing the methodology / target groups, we can take the results with a grain of salt and investigate re-doing the research with an hopefully improved process; comparing if/how the results differ would itself be likely informative
* if there aren't clear biases that emerge, that's more data we can collectively chew on, and possible starting points for future shared research

The main thing I think that would need particular care is in distinguishing how single-org research and shared research is presented with regard to the Community Group.

**Comment by robnyman** [comment]
I think that sounds fair. Thanks for your feedback!

**Comment by dontcallmedom** [comment]
#25 is our first example of such research results being published; let's close this issue for now, we can always re-open it if we find we want more guardrails
