### ISSUE TITLE
Reaching a broader CSS community for State of CSS 2022

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/developer-research#3]
Can this group do anything to get the next iteration of State of CSS in front of a broader community of CSS developers and designers? There's a concern that many people learned about the survey via State of JS, and it's unclear what kind of biases that introduces.

**Comment by dontcallmedom** [comment]
is there a more detailed analysis of the potential gaps in the community that state of CSS reached?

looking at https://2021.stateofcss.com/en-US/demographics, and https://2021.stateofcss.com/en-US/demographics/#source in particular, "State of JS" is less than 1% of the identified source of participants in the survey.

is there a shareable list of how, where and when the survey was publicized?

**Comment by foolip** [comment]
@LeaVerou when your plans for outreach for State of CSS 2022 start coming together, where will it be documented? I'd like to watch that space :)

**Comment by dontcallmedom** [comment]
State of CSS 2022 is past, so closing

**Comment by SachaG** [comment]
State of CSS 2023 is coming up next month by the way, we're doing it a bit earlier this year.
