### ISSUE TITLE
Learning more about web developers needs in the text and editing space

### ISSUE THREAD

**Issue by tayloregivens** [web-platform-dx/developer-research#34]
To help shape future investments in the text and editing space, we'd like to run a survey to understand web developer satisfaction and challenges with existing APIs. Below is an initial draft of the proposed survey content that we're looking for feedback from the CG on.

Survey prompt: We want to get feedback from web developers on the text and editing APIs listed below to help shape future investments in the space. 
 

**APIs shipping in at least one browser:**
  - Custom Highlight API
  - Static ranges
  - EditContext API
  - elementFromPoint/elementsFromPoint
  - caretPositionFromPoint
  - Async clipboard API
  - Web custom formats
  - Native SVG clipboard format
  - getComposedRanges
  - selectionchange event
  - writingsuggestions attribute

  _Response options for each API above:_
  - Never heard of it
  - Heard but never used it
  - Used it and satisfied
  - Used it and not satisfied
 
**API proposals:**
- highlightsFromPoint
- Bounding client rect for selection in input/textarea
- Range in input/textarea
- clipboardchange event
- placeElement

_Response Options for each API above:_
  - Never heard of it
  - Heard of it and interested
  - Heard of it and not interested
 

**Free form question:** Are there any text or editing related features that are difficult to implement?

@sanketj @captainbrosset

**Comment by captainbrosset** [comment]
Thank you Taylore.
Let me ping a few folks here.

@tidoust for visibility on this, as my co-chair on the group. This is a survey that our team at Edge would love to run in order to learn more about this space.
@Rumyra Taylore, Sanket, and I are considering leveraging an MDN short survey for this, and we'd love your opinion on the above.

**Comment by tidoust** [comment]
Thanks! Added to [next week's TPAC meeting's agenda](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit#heading=h.c0v2c091daal).

**Comment by Rumyra** [comment]
@captainbrosset thanks for notifying :) This looks to me like a good potential fit for MDN short surveys. I'll re-send the guidelines et al 👍

**Comment by tidoust** [comment]
See [relevant discussion in mdn/short-surveys](https://github.com/mdn/short-surveys/discussions/13)
